# Generated by Django 2.0.7 on 2018-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default='2018-08-08')),
                ('time_str', models.TimeField()),
                ('time_end', models.TimeField()),
            ],
        ),
    ]
